2021-03-27 14:31:18:INFO:process.py:43:Checking whether XTU is already running...
2021-03-27 14:31:18:INFO:xtucli.py:28:XTU process not found, launching now...
2021-03-27 14:31:23:INFO:xtucli.py:32:XTU is launched with PID: None
2021-03-27 14:31:23:INFO:process.py:32:Searching PID for XTU relevent process...
2021-03-27 14:31:23:INFO:process.py:39:{"XtuService.exe": 10528, "XtuUiLauncher.exe": 828, "PerfTune.exe": 16316}
2021-03-27 14:31:23:INFO:xtucli.py:33:{'XtuService.exe': 10528, 'XtuUiLauncher.exe': 828, 'PerfTune.exe': 16316}
2021-03-27 14:31:23:INFO:xtucli.py:45:Grabbing XTU window, retries(0/5)
2021-03-27 14:31:28:INFO:xtucli.py:45:Grabbing XTU window, retries(1/5)
